config/routes.rb
Rails.application.routes.draw do
  get 'main/login'
  post 'main/create' ,to: 'main#create' , as: 'check'
  get 'main/destroy'
  resources :users
  resources :scores
  resources :students
  get 'students/:id/edit_score' , to: 'students#edit_score' , as: 'aaa'
  #get 'adfa' ,to: 'students#new', as: 'somchai'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :debug

    def debug
        pp '---------------'
        pp session[:login]
        pp User.all
    end

  private 
    def login?
        return session[:login] == true
    end

    def must_login
        if login?
            return true
        else
            redirect_to main_login_path, alert: 'you must login before access next page'
        end
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login
  end

  def create
    # login = cho , password = dae
    a = User.where(login: params[:login]).first
    if a && a.authenticate(params[:password])
      redirect_to students_path
      session[:login] = true
    else
      redirect_to main_login_path, alert: 'login or password incorrect'
    end
  end

  def destroy
    reset_session
  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :must_login
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
    session[:from] = "score"
  end

  # GET /scores/1 or /scores/1.json
  def show
  
  end

  # GET /scores/new
  def new
   @score = Score.new
    #redirect_to aaa_path(@score.id)
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:subject, :point, :grade, :student_id)
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :has_student, only: %i[edit_score]
  before_action :must_login, only: %i[show new edit create update destroy]
  before_action :set_student, only: %i[ show edit update destroy edit_score]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # GET /students/1/edit_score
  def edit_score
    session[:from] = "student"
    @s = @student
    @scorestudent = Score.where(student_id:@s.id)

    sum = 0
    max = 0
    @maxsub = ""
    @scorestudent.each do |i|
      if i.point > max 
        max = i.point
        @maxsub = i.subject
      end 
      sum += i.point
    end
    
    if @scorestudent.count == 0 
      @avg = sum
    else
      @avg = sum/@scorestudent.count
    end

    @empty = true
    if !@scorestudent.blank?
      @empty = false
    end
  end


  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :dob, :student_no, :class_year)
    end

    #Check id of student is correct?
    def has_student
      if Student.where(id: params[:id]).empty?
        redirect_to students_path, notice: 'Not has this id in database'  
      else
        return true
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:login, :full_name, :password_digest, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lec09</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class = "container">
      <% flash.each do |type,msg|%>
        <% if type == 'notice' %>
          <div class='alert alert-success'>
            <%=msg%>
          </div>
        <%elsif type == 'alert'%>
          <div class='alert alert-danger'>
            <%=msg%>
          </div>
        <%end%>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/destroy.html.erb
<h1>destroy#main</h1>
<p>already log out</p>

app/views/main/login.html.erb
<h1>Main#login</h1>

<%= form_with url: check_path, data: {turbo: false} do |form| %>
    <p>
        <%=form.label :login , class: 'form-label' %>
        <%=form.text_field :login , class: 'form-control'%>
    </p>
    <p>
        <%=form.label :password , class: 'form-label'%>
        <%=form.password_field :password , class: 'form-control'%>
    </p>
    <%=form.submit :OK , class: 'btn btn-primary'%>
<%end%>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :point, style: "display: block" %>
    <%= form.number_field :point %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.text_field :grade %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Subject:</strong>
    <%= score.subject %>
  </p>

  <p>
    <strong>Point:</strong>
    <%= score.point %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= score.grade %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= score.student_id %>
  </p>

</div>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<% if session[:from] == "score" %>
  <%= simple_format("Student id = " + @score.student_id.to_s) %>
<%end%>

<%= render "form", score: @score %>

<br>

<div class='btn-group'>
    <%= link_to "Show this score", @score, class: 'btn btn-outline-primary' %> 
    <% if session[:from] == "student" %>
      <%= link_to "Back to students", students_path, class: 'btn btn-outline-primary' %>
    <% elsif session[:from] == "score" %> 
      <%= link_to "Back to scores", scores_path, class: 'btn btn-outline-primary'%>
    <%end%>
</div>

app/views/scores/index.html.erb
<h1>Scores</h1>

<% @scores.each do |score| %>
  <div class='card'>
    <div class='card-body'>
      <%= render score %>
      <%= link_to "Show this score", score , class: 'btn btn-outline-primary'%>
    </div>
  </div>
<% end %>


<%= link_to "New score", new_score_path , class: 'btn btn-success'%>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path , class: 'btn btn-primary'%>
</div>

app/views/scores/show.html.erb
<%= render @score %>

<div class='btn-group'>
  <%= link_to "Edit this score", edit_score_path(@score) , class: 'btn btn-outline-primary'%>
  
  <% if session[:from] == "student" %>
    <%= link_to "Back to student", students_path, class: 'btn btn-outline-primary' %>
  <% elsif session[:from] == "score" %> 
    <%= link_to "Back to scores", scores_path, class: 'btn btn-outline-primary' %>
  <%end%>
</div>

<br>
<br>
<%= button_to "Destroy this score", @score, method: :delete , class: 'btn btn-danger' %>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :student_no, style: "display: block" %>
    <%= form.text_field :student_no %>
  </div>

  <div>
    <%= form.label :class_year, style: "display: block" %>
    <%= form.number_field :class_year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= student.dob %>
  </p>

  <p>
    <strong>Student no:</strong>
    <%= student.student_no %>
  </p>

  <p>
    <strong>Class year:</strong>
    <%= student.class_year %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div class='btn-group'>
  <%= link_to "Show this student", @student , class: 'btn btn-outline-primary'%>
  <%= link_to "Back to students", students_path, class: 'btn btn-outline-primary' %>
</div>

app/views/students/edit_score.html.erb
<h1>Edit Score</h1>

<%if !@empty %>
    <% @scorestudent.each do |score| %>
        <div class='card'>
            <div class='class-body'>
                <%= render score %>
                <div class='row row-cols-auto'>
                    <div class='col'>
                        <% if session[:login] %>
                            <%= button_to "Edit Score", edit_score_path(@s.id) , class: 'btn btn-secondary', method: :get %>
                        <%end%>
                    </div>
                    <div class='col'>
                        <%= button_to "Delete Score", score, class: 'btn btn-danger', method: :delete %>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
<%end%>

<br>
<div class='card'>
    <h4 class='card-header'>Summary</h4>
    <div class='class-body'>
        <p class='card-text'><%= "Average Score " + @avg.to_s %></p>
        <p class='card-text'><%= "Max Subject Score " + @maxsub.to_s %></p>
        <%= button_to "New Score", new_score_path, class: 'btn btn-success', method: :get %>
    </div>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <%= render student %>
        <div class = 'row row-cols-2'>
          <%= link_to "Show this student", student , class: 'btn btn-primary'%>
          <% if session[:login] %>
            <%= link_to "Edit Score", aaa_path(student.id) , stu:student , class: 'btn btn-light'%>
          <%end%>
        </div>
      </div>
    </div>
    <br>
  <%end%>
</div>

<%= link_to "New student", new_student_path , class: 'btn btn-success' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path , class: 'btn btn-success' %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div class='btn-group'>
  <%= link_to "Edit this student", edit_student_path(@student) , class:'btn btn-outline-primary'%>
  <%= link_to "Back to students", students_path , class: 'btn btn-outline-primary'%>

</div>

<br>
<br>
<%= button_to "Destroy this student", @student, method: :delete , class: 'btn btn-danger' %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.label :admin, style: "display: block" %>
    <%= form.check_box :admin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Login:</strong>
    <%= user.login %>
  </p>

  <p>
    <strong>Full name:</strong>
    <%= user.full_name %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>